name: microsoft_kiota_bundle
description: "Provides a bundle of all the default Kiota implementations for easy consumption."
version: 0.0.1-pre.1
homepage: https://github.com/microsoft/kiota-dart/tree/main/packages/microsoft_kiota_bundle
repository: https://github.com/microsoft/dart_kiota

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  microsoft_kiota_abstractions: '>=0.0.1 <1.0.0'
  microsoft_kiota_http: '>=0.0.1 <1.0.0'
  microsoft_kiota_serialization_text: '>=0.0.1 <1.0.0'
  microsoft_kiota_serialization_form: '>=0.0.1 <1.0.0'
  microsoft_kiota_serialization_json: '>=0.0.1 <1.0.0'
  microsoft_kiota_serialization_multipart: '>=0.0.1 <1.0.0'

dev_dependencies:
  strict: ^2.1.0
  test: ^1.25.12
  mockito: ^5.4.4
  build_runner: any
  http: ^1.2.2
