name: microsoft_kiota_serialization_text
description: "Provides parsing and serialization support for the `text/plain` content type."
version: 0.0.1-pre.1
homepage: https://github.com/microsoft/kiota-dart/tree/main/packages/microsoft_kiota_serialization_text
repository: https://github.com/microsoft/dart_kiota

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  microsoft_kiota_abstractions:
    path: ../microsoft_kiota_abstractions
  uuid: ^4.5.1

dev_dependencies:
  strict: ^2.1.0
  test: ^1.25.8
