name: microsoft_kiota_serialization_text
description: "Provides parsing and serialization support for the `text/plain` content type."
version: 0.0.1-pre.1
homepage: https://github.com/kiota-community/dart_kiota/tree/main/packages/microsoft_kiota_serialization_text
repository: https://github.com/kiota-community/dart_kiota
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  microsoft_kiota_abstractions: '>=0.0.1 <1.0.0'
  uuid: ^4.5.1

dev_dependencies:
  strict: ^2.1.0
  test: ^1.25.12
