name: microsoft_kiota_serialization_multipart
description: "Provides parsing and serialization support for the `multipart/form-data` content type."
version: 0.0.1-pre.1
homepage: https://github.com/kiota-community/dart_kiota/tree/main/packages/microsoft_kiota_serialization_multipart
repository: https://github.com/kiota-community/dart_kiota
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  http: ^1.2.2
  microsoft_kiota_abstractions: '>=0.0.1 <1.0.0'
  typed_data: ^1.4.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: any
  microsoft_kiota_serialization_json: '>=0.0.1 <1.0.0'
  mockito: ^5.4.4
  strict: ^2.1.0
  test: ^1.25.12
