name: microsoft_kiota_serialization_json
description: "Provides parsing and serialization support for the `application/json` content type."
version: 0.0.1-pre.1
homepage: https://github.com/microsoft/kiota-dart/tree/main/packages/microsoft_kiota_serialization_json
repository: https://github.com/microsoft/dart_kiota

environment:
  sdk: '>=3.2.6 <4.0.0'

# Add regular dependencies here.
dependencies:
  microsoft_kiota_abstractions:
    path: ../microsoft_kiota_abstractions
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.9
  strict: ^2.0.0
  test: ^1.25.2
