name: microsoft_kiota_serialization_json
description: Provides parsing and serialization support for the `application/json` content type.
version: 0.0.1-pre.1
repository: https://github.com/ricardoboss/dart_kiota
homepage: https://github.com/ricardoboss/dart_kiota/tree/main/packages/microsoft_kiota_serialization_json
publish_to: 'none'

environment:
  sdk: ^3.6.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  microsoft_kiota_abstractions:
    path: ../microsoft_kiota_abstractions
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.9
  strict: ^2.0.0
  test: ^1.25.2
